### ISSUE TITLE
crossbridge and C++11

### ISSUE THREAD

**Issue by pol2095** [adobe-flash/crossbridge#70]
Hello,

Is-it possible to use C++11 using crossbridge ?

Thanks

**Comment by JoeDupuis** [comment]
This project have been abandoned by adobe a long time ago. 
The crossbridge community fork is a bit ahead. I believe yes it support C++11, but even the crossbridge community port is unmaintained at this point.

**Comment by JoeDupuis** [comment]
Here's the community fork https://github.com/crossbridge-community/crossbridge

**Comment by pol2095** [comment]
I use crossbridge community 15.0.0 but C++11 is not supported
`std::to_string(42);` return an error

**Comment by ROBERT-MCDOWELL** [comment]
@pol2095 
I think it would be worth for you to join Ruffle project
https://github.com/ruffle-rs/ruffle
the goal is to replace Flash plugin keeping intact Flash API, SWF and AVM1 / AVM2
So you will be able to integrate your C++ in webassembly as well.
WASM is the next Web binary standard container. Project like Crossbridge is abandonned in favour of webassembly.

**Comment by pol2095** [comment]
Thanks, but it's for a Air project, webassembly is not a solution.

**Comment by ROBERT-MCDOWELL** [comment]
Well, Air is depracated too in favour of webassembly.

**Comment by pol2095** [comment]
webassembly is for the web, for an app is a deprecated too, I prefer Unity instead.

**Comment by JoeDupuis** [comment]
Not necessarily. There is node and electron that allow you to target desktop and not browser.

Depending on the type of project, unity is possibly a good solution.

But as others have said, I would not recommend starting a greenfield project on anything flash/air related.

**Comment by pol2095** [comment]
It's not for a new project, I need to add functionnality to my app.

**Comment by pol2095** [comment]
I try to implement an external library in C++11 using [Crossbridge 1.1.0](https://sourceforge.net/projects/crossbridge/files/) on Mac but it’s not finalized and I have this error :

> /Users/user/Desktop/Projets/crossbridge/flascc/sdk/usr/bin/…/…/usr/lib/libc.a: error: undefined reference to ‘__openat’
> /Users/user/Desktop/Projets/crossbridge/flascc/sdk/usr/bin/…/…/usr/lib/libc.a: error: undefined reference to ‘_fstatat’
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [T05] Error 1

Thanks
